### PR TITLE
Attempt to add dev dependencies and build process (v2)

### PR DESCRIPTION
**Pull request by ahaarnos**
###### (message copied straight from the first [attempt](https://github.com/mahnunchik/markerclustererplus/pull/12))

I was in the process of trying to submit a PR to correct the http/https issue when I found I didn't know how to re-build the `_packed.js` and `.min.js` versions of the file.

The original project used packer to create the `_packed.js` file, but it seems you've switched to using a different tool (in fact, the `_.packed.js` file in the repo right now looks more like it should be the `.min.js` file).

I've added a gulp-based build process using the npm version of [packer](https://github.com/evanw/packer) to build the `_packed.js` file, which you may or may not find useful -- and you can see the resulting file in this PR. If you accept this, I'd love to see the build extended to add however you're creating the current `.min.js` (partially because it doesn't seem very minified at all right now).

If you don't accept this, can you please offer some devDependencies / build process either via npm/bower and grunt/gulp?

### CODE REVIEW

**Comment by mahnunchik** [comment]
Hi @ahaarnos,

I've just realized that we have two versions of 'strangely' minified files.

I would not want to add the build system as dependancy. So I think there will be enough to use npm scripts and for example `uglify` module.

What do you think about the following changes:
* Remove `markerclusterer.map.js`, `markerclusterer.min.js`, and `markerclusterer_packed.js`
* Add folder `dist`
* Add build script to package.json like this: `"build": "uglifyjs src/markerclusterer.js -o dist/markerclusterer.min.js"`

**Comment by mahnunchik** [comment]
I have implemented it in this branch: https://github.com/mahnunchik/markerclustererplus/tree/build-script

What do you think?

**Comment by ahaarnos** [comment]
I'm cool with this.

Are you okay with making a breaking change without any pre-warning?

If not, I suggest having the build produce the `_packed.js` and `.min.js` versions still in the src folder, in addition to the properly minified version in dist. Then append a console.warn to the those two (redundant) files, notifying people that they're deprecated, and will soon be removed.

If you switch to using [UglifyJS2](https://github.com/mishoo/UglifyJS2) (same author as the original), you can use the `--prepend` option to add the deprecation warning to the two legacy files:


``` javascript
// note, I haven't had time to test this... and I added a main declaration
"scripts": {
  "main": "dist/markerclusterer.js",
  "build:min": "uglifyjs src/markerclusterer.js --compress --output dist/markerclusterer.js"
  "build:legacy_packaged": "uglifyjs src/markerclusterer.js --compress --output src/markerclusterer_packaged.js --prepend \"console.warn('This file has been deprecated and will be removed in the next release.')\"",
  "build:legacy_min": "uglifyjs src/markerclusterer.js --compress --output src/markerclusterer.min.js --prepend \"console.warn('This file has been deprecated and will be removed in the next release.')\"",
  "build": "npm run build:min && npm run build:legacy_packaged && build:legacy_min"
}
```

In general, it seems like UglifyJS2 is the way I would go, personally. And I wholly condone moving to having a `dist` directory where build products are stored.

**Comment by mahnunchik** [comment]
It already uses [UglifyJS2](https://github.com/mahnunchik/markerclustererplus/blob/build-script/package.json#L14).

I wanted to make major release, but now I think that warning in these files and a minor release is more suitable option for this kind of changes.

Thanks!

**Comment by mahnunchik** [comment]
I've preferred to leave the two scripts:
* `build`
* `build:legacy`

**Pull request closed without merging**
